apiVersion: v1
kind: Secret
metadata:
  name: fast-food-secrets
type: Opaque
data:
  userId: MjAyMzIwMjU1OA==
  externalPosId: RklBUFJQT1MwMDE=
  accessToken: QVBQX1VTUi00NDg1NTAyMzkxNTMzNDE4LTEwMDYxMy00ZDM4ZWFiNWNhZjQzNjFlZTI1ZDZiNTgwNTcxYjVmYi0yMDIzMjAyNTU4  # Valor codificado em base64
