name: Deploy Kubernetes Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f kubernetes/
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
