name: Deploy Application to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/fast-food-system:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/fast-food-system:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
